### ISSUE TITLE
Paginated Search in Plugin-Sidebar (Growing List)

### ISSUE THREAD

**Issue by infacc** [UST-QuAntiL/qhana-ui#58]
In order to search through not only the first 25 plugins in the plugin sidebar, the user needs to click the `load more` button.

The plugins inside a template tab in the plugin sidebar are paginated. When the number of plugins exceeds the page size (`25`), the user needs to click the corresponding `load more` button. However, when searching for a plugin and thus reducing the number of displayed plugins, the user still needs to press the `load more` button to filter the subsequent 25 plugins.

It may be convenient to always show the first 25 matching plugins when searching.

<details>
<summary>Screenshots</summary>

![growing-list-search](https://github.com/UST-QuAntiL/qhana-ui/assets/33042539/4a62e83d-fa6a-41b1-adc6-68345e014717)
![growing-list-search](https://github.com/UST-QuAntiL/qhana-ui/assets/33042539/2cafd7ff-0f13-4a8b-9326-5a1d299fa9ba)
</details>

**Comment by buehlefs** [comment]
There is no easy way around this. There are a few "solutions" worth considering:

1. Search server side -> this will complicate the growing list component implementation dramatically
2. Auto load more plugins -> can be done with slight modifications to the growing list (may also be nice if it auto triggers on search)
3. Load more plugins -> server side supports larger pages with up to 100 items; just set the relevant query parameter; only moves the problem

However, it is a bad idea to have too many plugins in a single list anyway, so ui templates should use more tabs if a tab has too many plugins. That was the whole point of them.
